
    create table backups (
        backup_file_id bigint,
        created_at timestamp(6) with time zone,
        ended_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        started_at timestamp(6) with time zone not null,
        status varchar(20) not null check ((status in ('IN_PROGRESS','COMPLETED','FAILED','SKIPPED'))),
        worker varchar(50) not null,
        error_summary TEXT,
        primary key (id)
    );

    create table change_log_diffs (
        change_log_id bigint not null,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        after_value TEXT,
        before_value TEXT,
        property_name varchar(255) not null,
        primary key (id)
    );

    create table change_logs (
        created_at timestamp(6) with time zone,
        employee_id bigint not null,
        id bigint generated by default as identity,
        profile_image_id_snapshot bigint,
        ip_address varchar(45) not null,
        employee_number_snapshot varchar(50) not null,
        memo varchar(500),
        employee_name_snapshot varchar(255) not null,
        type varchar(255) not null check ((type in ('CREATED','UPDATED','DELETED'))),
        primary key (id)
    );

    create table department (
        established_date date not null,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        description varchar(255) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table employees (
        hire_date date not null,
        status smallint not null check ((status between 0 and 2)),
        created_at timestamp(6) with time zone,
        department_id bigint,
        files_id bigint unique,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        employee_number varchar(255) not null,
        name varchar(255) not null,
        position varchar(255) not null,
        primary key (id)
    );

    create table files (
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        size bigint not null,
        content_type varchar(255) not null,
        original_name varchar(255) not null,
        storage_path varchar(255) not null,
        stored_name varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists backups 
       add constraint FK7r1n4nfd1itl1odv2i9gkqa4d 
       foreign key (backup_file_id) 
       references files;

    alter table if exists change_log_diffs 
       add constraint FKbe7jjmt4xaxdjx2sj1k1xn837 
       foreign key (change_log_id) 
       references change_logs;

    alter table if exists employees 
       add constraint FK8if1byloc650qvkaxabyjveap 
       foreign key (department_id) 
       references department;

    alter table if exists employees 
       add constraint FKkvdfh20m1ec8g52af6vcxnt8r 
       foreign key (files_id) 
       references files;

    create table backups (
        backup_file_id bigint,
        created_at timestamp(6) with time zone,
        ended_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        started_at timestamp(6) with time zone not null,
        status varchar(20) not null check ((status in ('IN_PROGRESS','COMPLETED','FAILED','SKIPPED'))),
        worker varchar(50) not null,
        error_summary TEXT,
        primary key (id)
    );

    create table change_log_diffs (
        change_log_id bigint not null,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        after_value TEXT,
        before_value TEXT,
        property_name varchar(255) not null,
        primary key (id)
    );

    create table change_logs (
        created_at timestamp(6) with time zone,
        employee_id bigint not null,
        id bigint generated by default as identity,
        profile_image_id_snapshot bigint,
        ip_address varchar(45) not null,
        employee_number_snapshot varchar(50) not null,
        memo varchar(500),
        employee_name_snapshot varchar(255) not null,
        type varchar(255) not null check ((type in ('CREATED','UPDATED','DELETED'))),
        primary key (id)
    );

    create table department (
        established_date date not null,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        description varchar(255) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table employees (
        hire_date date not null,
        status smallint not null check ((status between 0 and 2)),
        created_at timestamp(6) with time zone,
        department_id bigint,
        files_id bigint unique,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        employee_number varchar(255) not null,
        name varchar(255) not null,
        position varchar(255) not null,
        primary key (id)
    );

    create table files (
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        size bigint not null,
        content_type varchar(255) not null,
        original_name varchar(255) not null,
        storage_path varchar(255) not null,
        stored_name varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists backups 
       add constraint FK7r1n4nfd1itl1odv2i9gkqa4d 
       foreign key (backup_file_id) 
       references files;

    alter table if exists change_log_diffs 
       add constraint FKbe7jjmt4xaxdjx2sj1k1xn837 
       foreign key (change_log_id) 
       references change_logs;

    alter table if exists employees 
       add constraint FK8if1byloc650qvkaxabyjveap 
       foreign key (department_id) 
       references department;

    alter table if exists employees 
       add constraint FKkvdfh20m1ec8g52af6vcxnt8r 
       foreign key (files_id) 
       references files;
